# monitoring/promtail-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # VPN Handler logs
  - job_name: vpn-handler-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: python-scraper
          component: VpnHandler
          __path__: /app/logs/vpnhandler.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            event_type: event_type
            message: message
      - labels:
          level:
          event_type:
      - timestamp:
          source: timestamp
          format: RFC3339

  # System logs (optional)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log